services:
  postgres:
    image: postgres:16-alpine
    container_name: fairbank-postgres
    environment:
      POSTGRES_DB: fairbank
      POSTGRES_USER: fairbank_admin
      POSTGRES_PASSWORD: fairbank_secret_2026
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: >
      postgres
        -c shared_buffers=128MB
        -c effective_cache_size=384MB
        -c work_mem=8MB
        -c log_statement=all
        -c log_connections=on
        -c log_disconnections=on
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fairbank_admin -d fairbank"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  identity-api:
    build:
      context: .
      dockerfile: src/Services/Identity/FairBank.Identity.Api/Dockerfile
    container_name: fairbank-identity-api
    ports:
      - "8001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=fairbank;Username=fairbank_app;Password=fairbank_app_2026;Search Path=identity_service"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  accounts-api:
    build:
      context: .
      dockerfile: src/Services/Accounts/FairBank.Accounts.Api/Dockerfile
    container_name: fairbank-accounts-api
    ports:
      - "8002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=fairbank;Username=fairbank_app;Password=fairbank_app_2026;Search Path=accounts_service"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  api-gateway:
    build:
      context: .
      dockerfile: src/FairBank.ApiGateway/Dockerfile
    container_name: fairbank-api-gateway
    ports:
      - "5000:8080"
    depends_on:
      - identity-api
      - accounts-api
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
